name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    # container:
    #   image: clojure:openjdk-14-tools-deps
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Install clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
          chmod +x linux-install-1.10.1.536.sh
          sudo ./linux-install-1.10.1.536.sh
      - name: Cache m2
        uses: actions/cache@v1.1.2
        with:
          path: /root/.m2
          key: root-m2-${{ hashFiles('deps.edn') }}
      - name: Run cloverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash script/coverage.sh
          bash <(curl -s https://codecov.io/bash)
