name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: coverage-m2-${{ hashFiles('deps.edn') }}-v1
      - name: Run cloverage
        run: make coverage
      - name: Upload reports
        uses: codecov/codecov-action@v3
