name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    # container:
    #   image: clojure:openjdk-14-tools-deps
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: coverage-m2-${{ hashFiles('deps.edn') }}-v1
      - name: Run cloverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash script/coverage.sh
          bash <(curl -s https://codecov.io/bash)
