name: dependencies
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquidz/antq-action@v1
        with:
          excludes: 'org.clojure/tools.deps.alpha lambdaisland/deep-diff2'
