name: docker
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
         echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
         docker pull ghcr.io/liquidz/antq:latest
      # FIXME docker build . -t ...:latest -t ...:ref
      - name: build latest
        run: |
         docker build . -t ghcr.io/liquidz/antq:latest --cache-from ghcr.io/liquidz/antq:latest
         docker push ghcr.io/liquidz/antq:latest
      - name: build for tag
        if: contains(github.ref, 'refs/tags/')
        run: |
         TAG_NAME=$(echo "${{ github.ref }}" | sed 's!refs/tags/!!')
         docker build . -t ghcr.io/liquidz/antq:${TAG_NAME} --cache-from ghcr.io/liquidz/antq:latest
         docker push ghcr.io/liquidz/antq:${TAG_NAME}
